# Arrays:

Its a  package in python mainly used for scientific computing, here we use arrays.

## Diffenrence between list and array

---
\

### List


*   It's a collection of homogenous or heterogenous values enclosed between pair of square brackets
*   In List it's not possible to perform Operations like multiplication, substraction etc. between two list collections
*   List follows discontinous memory.
*   List is slower than arrays.
*  It's an inbuilt collection


### Arrays

*   It's the collection of homogenous data elements.
*   In array it's possible to perform Operations like multiplication, substraction etc. between two array collections
*   List follows continous memory.
*   List is faster than lists.
*   We need to import numpy to use arrays





###Importing Numpy

In [2]:
import numpy as np

###Syntax of creating an array:

```
np.array(val/var)

```


### Array Operations

In [6]:
print(np.array([1,2,3]))
print(np.array([1,2,3.5]))
print(np.array([1,2,3+4j]))
print(np.array([1,2,3+4j,'rohith']))
print(np.array([1,2.5,3+4j]))

[1 2 3]
[1.  2.  3.5]
[1.+0.j 2.+0.j 3.+4.j]
['1' '2' '(3+4j)' 'rohith']
[1. +0.j 2.5+0.j 3. +4.j]


In [8]:
x = np.array([1,2.4,5])
x.dtype

[1 2 3]


dtype('float64')

### D-Dimentional Arrays
*  **ndim** is an attribute which gives the dimention of an array


*   Usually arrays can be 1D, 2D ... nD,
 but 1D and 2D are used very frequently.
```
var.ndim
```



####1D- Array

In [29]:
a = np.array([1,2,3])
print(a)
print("Dimentions = ",a.ndim)

[1 2 3]
Dimentions =  1


####2D- Array

In [28]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("Dimentions = ",b.ndim)

[[1 2 3]
 [4 5 6]]
Dimentions =  2


####3D- Array

In [30]:
c = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(c)
print("Dimentions = ",c.ndim)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
Dimentions =  3
